# id: "urn:ngsi-ld:vehicle:someVehicle"

# mqtt:
#   broker: myMQTTBroker
#   port: 3306
#   user: someUser
#   password: somePassword
#   periodic_interval: 5
#   topics:
#     command: v1/vehicle/{vehicle_id}/command
#     telemetry: v1/vehicle/{vehicle_id}/telemetry
